// Code generated by "stringer -type=opType"; DO NOT EDIT.

package schemachange

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[addColumn-0]
	_ = x[addCheckConstraint-1]
	_ = x[addForeignKeyConstraint-2]
	_ = x[addUniqueConstraint-3]
	_ = x[createIndex-4]
	_ = x[createSequence-5]
	_ = x[createTable-6]
	_ = x[createTableAs-7]
	_ = x[createView-8]
	_ = x[createEnum-9]
	_ = x[createSchema-10]
	_ = x[dropColumn-11]
	_ = x[dropColumnDefault-12]
	_ = x[dropColumnNotNull-13]
	_ = x[dropColumnStored-14]
	_ = x[dropConstraint-15]
	_ = x[dropIndex-16]
	_ = x[dropSequence-17]
	_ = x[dropTable-18]
	_ = x[dropView-19]
	_ = x[dropSchema-20]
	_ = x[renameColumn-21]
	_ = x[renameIndex-22]
	_ = x[renameSequence-23]
	_ = x[renameTable-24]
	_ = x[renameView-25]
	_ = x[setColumnDefault-26]
	_ = x[setColumnNotNull-27]
	_ = x[setColumnType-28]
	_ = x[insertRow-29]
	_ = x[validate-30]
}

const _opType_name = "addColumnaddCheckConstraintaddForeignKeyConstraintaddUniqueConstraintcreateIndexcreateSequencecreateTablecreateTableAscreateViewcreateEnumcreateSchemadropColumndropColumnDefaultdropColumnNotNulldropColumnStoreddropConstraintdropIndexdropSequencedropTabledropViewdropSchemarenameColumnrenameIndexrenameSequencerenameTablerenameViewsetColumnDefaultsetColumnNotNullsetColumnTypeinsertRowvalidate"

var _opType_index = [...]uint16{0, 9, 27, 50, 69, 80, 94, 105, 118, 128, 138, 150, 160, 177, 194, 210, 224, 233, 245, 254, 262, 272, 284, 295, 309, 320, 330, 346, 362, 375, 384, 392}

func (i opType) String() string {
	if i < 0 || i >= opType(len(_opType_index)-1) {
		return "opType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _opType_name[_opType_index[i]:_opType_index[i+1]]
}
